apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: distiller-data
  labels:
    ensembl.platform.app.name: distiller
spec:
  storageClassName: standard-nfs-production
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi